Updated configure script
Signed-off-by: Janos SUTO <sj@acts.hu>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -651,7 +651,6 @@ DATAROOTDIR
 LIBEXECDIR
 DATADIR
 CFGDIR
-PSQL_CONFIG
 MYSQL_CONFIG
 iv
 id_bin
@@ -724,7 +723,6 @@ enable_compat_layout
 enable_clamd
 enable_memcached
 enable_tweak_sent_time
-with_database
 with_piler_user
 '
       ac_precious_vars='build_alias
@@ -1360,7 +1358,6 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-database[=mysql]  select the used database, currently mysql only (default: none)
   --with-piler-user=username      what user the piler daemon shall be run as
 
 Some influential environment variables:
@@ -3580,8 +3577,9 @@ have_psql="no"
 have_tre="no"
 have_zip="no"
 have_zlib="no"
-have_tcpwrappers="no"
 have_tweak_sent_time="no"
+
+database=""
 
 pdftotext="no"
 catdoc="no"
@@ -3673,106 +3671,6 @@ else $as_nop
   want_memcached="no"
 fi
 
-
-
-
-       for ac_header in tcpd.h
-do :
-  ac_fn_c_check_header_compile "$LINENO" "tcpd.h" "ac_cv_header_tcpd_h" "$ac_includes_default"
-if test "x$ac_cv_header_tcpd_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_TCPD_H 1" >>confdefs.h
- have_tcpwrappers=yes
-else $as_nop
-  echo "tcpd.h is not found"
-fi
-
-done
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for hosts_access in -lwrap" >&5
-printf %s "checking for hosts_access in -lwrap... " >&6; }
-if test ${ac_cv_lib_wrap_hosts_access+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lwrap  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char hosts_access ();
-int
-main (void)
-{
-return hosts_access ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_wrap_hosts_access=yes
-else $as_nop
-  ac_cv_lib_wrap_hosts_access=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_wrap_hosts_access" >&5
-printf "%s\n" "$ac_cv_lib_wrap_hosts_access" >&6; }
-if test "x$ac_cv_lib_wrap_hosts_access" = xyes
-then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for hosts_access in -lwrap" >&5
-printf %s "checking for hosts_access in -lwrap... " >&6; }
-if test ${ac_cv_lib_wrap_hosts_access+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lwrap  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char hosts_access ();
-int
-main (void)
-{
-return hosts_access ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_wrap_hosts_access=yes
-else $as_nop
-  ac_cv_lib_wrap_hosts_access=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_wrap_hosts_access" >&5
-printf "%s\n" "$ac_cv_lib_wrap_hosts_access" >&6; }
-if test "x$ac_cv_lib_wrap_hosts_access" = xyes
-then :
-  have_tcpwrappers=yes
-else $as_nop
-  echo "libwrap is not found"; have_tcpwrappers=no
-fi
-
-fi
-ac_cv_lib_wrap=ac_cv_lib_wrap_main
-
-if test "$have_tcpwrappers" = "no"; then
-   echo "can't find either tcpd.h or libwrap. Tcpwrappers support is disabled";
-fi
 
 
 # Check whether --enable-tweak-sent-time was given.
@@ -4367,160 +4265,7 @@ if test "$have_zlib" = "no"; then
 fi
 
 
-
-# Check whether --with-database was given.
-if test ${with_database+y}
-then :
-  withval=$with_database;
-   if test "$withval" != "no" -a "$withval" != "yes"; then
-      DATABASE=$withval
-   fi
-
-
-   if test "$withval" = "mysql"; then
-
-      # Extract the first word of "mysql_config", so it can be a program name with args.
-set dummy mysql_config; ac_word=$2
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-printf %s "checking for $ac_word... " >&6; }
-if test ${ac_cv_prog_MYSQL_CONFIG+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  if test -n "$MYSQL_CONFIG"; then
-  ac_cv_prog_MYSQL_CONFIG="$MYSQL_CONFIG" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  case $as_dir in #(((
-    '') as_dir=./ ;;
-    */) ;;
-    *) as_dir=$as_dir/ ;;
-  esac
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
-    ac_cv_prog_MYSQL_CONFIG="yes"
-    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
-
-fi
-fi
-MYSQL_CONFIG=$ac_cv_prog_MYSQL_CONFIG
-if test -n "$MYSQL_CONFIG"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $MYSQL_CONFIG" >&5
-printf "%s\n" "$MYSQL_CONFIG" >&6; }
-else
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
-fi
-
-
-
-      if test x$MYSQL_CONFIG = xyes; then
-         have_mysql="yes"
-      fi
-
-      if test "$have_mysql" = "yes"; then
-
-         sql_includes=`mysql_config --cflags`
-         sql_libs=`mysql_config --libs_r`
-         sql_obj="mysql.o"
-
-         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for main in -lguide" >&5
-printf %s "checking for main in -lguide... " >&6; }
-if test ${ac_cv_lib_guide_main+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lguide  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-
-int
-main (void)
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_guide_main=yes
-else $as_nop
-  ac_cv_lib_guide_main=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_guide_main" >&5
-printf "%s\n" "$ac_cv_lib_guide_main" >&6; }
-if test "x$ac_cv_lib_guide_main" = xyes
-then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for _intel_fast_memset in -lguide" >&5
-printf %s "checking for _intel_fast_memset in -lguide... " >&6; }
-if test ${ac_cv_lib_guide__intel_fast_memset+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lguide  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char _intel_fast_memset ();
-int
-main (void)
-{
-return _intel_fast_memset ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_guide__intel_fast_memset=yes
-else $as_nop
-  ac_cv_lib_guide__intel_fast_memset=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_guide__intel_fast_memset" >&5
-printf "%s\n" "$ac_cv_lib_guide__intel_fast_memset" >&6; }
-if test "x$ac_cv_lib_guide__intel_fast_memset" = xyes
-then :
-  have_icc_guide=yes
-else $as_nop
-  have_icc_guide=no
-fi
-
-fi
-ac_cv_lib_guide=ac_cv_lib_guide_main
-
-      else
-         echo "MySQL support is not found"
-         exit 1;
-      fi
-   fi
-
-
-   if test "$withval" = "mariadb"; then
-
-      # Extract the first word of "mariadb_config", so it can be a program name with args.
+# Extract the first word of "mariadb_config", so it can be a program name with args.
 set dummy mariadb_config; ac_word=$2
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
 printf %s "checking for $ac_word... " >&6; }
@@ -4563,35 +4308,29 @@ fi
 
 
 
-      if test x$MYSQL_CONFIG = xyes; then
-         have_mysql="yes"
-      fi
+if test x$MYSQL_CONFIG = xyes; then
+   have_mysql="yes"
+fi
 
-      if test "$have_mysql" = "yes"; then
+if test "$have_mysql" = "yes"; then
+   sql_includes=`mariadb_config --cflags`
+   sql_libs=`mariadb_config --libs_r`
+   sql_obj="mysql.o"
+   database="mariadb"
+   echo "Found mariadb"
+fi
 
-         sql_includes=`mariadb_config --cflags`
-         sql_libs=`mariadb_config --libs_r`
-         sql_obj="mysql.o"
-
-      else
-         echo "mariadb_config is not found, please install \"MariaDB Client Library for C 1.0.0 Stable\", see https://downloads.mariadb.org/client-native/1.0.0/"
-         exit 1;
-      fi
-   fi
-
-
-   if test "$withval" = "psql"; then
-
-      # Extract the first word of "pg_config", so it can be a program name with args.
-set dummy pg_config; ac_word=$2
+if test "$have_mysql" = "no"; then
+   # Extract the first word of "mysql_config", so it can be a program name with args.
+set dummy mysql_config; ac_word=$2
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
 printf %s "checking for $ac_word... " >&6; }
-if test ${ac_cv_prog_PSQL_CONFIG+y}
+if test ${ac_cv_prog_MYSQL_CONFIG+y}
 then :
   printf %s "(cached) " >&6
 else $as_nop
-  if test -n "$PSQL_CONFIG"; then
-  ac_cv_prog_PSQL_CONFIG="$PSQL_CONFIG" # Let the user override the test.
+  if test -n "$MYSQL_CONFIG"; then
+  ac_cv_prog_MYSQL_CONFIG="$MYSQL_CONFIG" # Let the user override the test.
 else
 as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
@@ -4604,7 +4343,7 @@ do
   esac
     for ac_exec_ext in '' $ac_executable_extensions; do
   if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
-    ac_cv_prog_PSQL_CONFIG="yes"
+    ac_cv_prog_MYSQL_CONFIG="yes"
     printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -4614,37 +4353,33 @@ IFS=$as_save_IFS
 
 fi
 fi
-PSQL_CONFIG=$ac_cv_prog_PSQL_CONFIG
-if test -n "$PSQL_CONFIG"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $PSQL_CONFIG" >&5
-printf "%s\n" "$PSQL_CONFIG" >&6; }
+MYSQL_CONFIG=$ac_cv_prog_MYSQL_CONFIG
+if test -n "$MYSQL_CONFIG"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $MYSQL_CONFIG" >&5
+printf "%s\n" "$MYSQL_CONFIG" >&6; }
 else
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
 printf "%s\n" "no" >&6; }
 fi
 
 
-
-      if test x$PSQL_CONFIG = xyes; then
-         have_psql="yes"
-      fi
-
-      if test "$have_psql" = "yes"; then
-
-         sql_includes="-I`pg_config --includedir`"
-         sql_libs="-L`pg_config --libdir`"
-         sql_obj="psql.o"
-
-      else
-         echo "PSQL support is not found"
-         exit 1;
-      fi
+   if test x$MYSQL_CONFIG = xyes; then
+      have_mysql="yes"
    fi
 
-
+   if test "$have_mysql" = "yes"; then
+      sql_includes=`mysql_config --cflags`
+      sql_libs=`mysql_config --libs_r`
+      sql_obj="mysql.o"
+      database="mysql"
+      echo "Found mysql"
+   fi
 fi
 
-
+if test "$have_mysql" = "no"; then
+   echo "MySQL support is not found"
+   exit 1
+fi
 
 
 if test z`which timeout 2>/dev/null` != "z"; then
@@ -4762,14 +4497,6 @@ printf "%s\n" "#define DATAROOTDIR \"$dataroot_dir\"" >>confdefs.h
 
 
 
-if test "$have_mysql" = "no" && test "$have_psql" = "no"; then
-   echo
-   echo "please specify the used database with --with-database=..."
-   echo
-   exit 1
-fi
-
-
 
 if test "$os" = "FreeBSD"; then
    defs="$defs -DFREEBSD"
@@ -4819,11 +4546,7 @@ fi
 
 
 if test "$have_mysql" = "yes"; then
-   echo "database: mysql"
-fi
-
-if test "$have_psql" = "yes"; then
-   echo "database: psql"
+   echo "database: $database"
 fi
 
 
