Added support for manticore
Signed-off-by: Janos SUTO <sj@acts.hu>

diff --git a/util/indexer.delta.sh.in b/util/indexer.delta.sh.in
--- a/util/indexer.delta.sh.in
+++ b/util/indexer.delta.sh.in
@@ -6,10 +6,17 @@ DELTATMPFILE=/var/run/piler/delta.indexer.tmp
 INDEXER="indexer --config SYSCONFDIR/piler/sphinx.conf"
 PRIORITY=mail.info
 TOUCHFILE=/var/piler/stat/indexer
+CONFIG_FILE=sphinx.conf
 
-if [ -f $MAINTMPFILE ]; then echo "INDEXER ERROR: indexer merging to main index is already running. It started at "`cat $MAINTMPFILE` | logger -p $PRIORITY ; exit 1; fi
+if [[ -f SYSCONFDIR/piler/MANTICORE ]]; then
+   CONFIG_FILE=manticore.conf
+fi
 
-if [ -f $DELTATMPFILE ]; then echo "INDEXER ERROR: delta indexing and merging is already running. It started at "`cat $DELTATMPFILE` | logger -p $PRIORITY ; exit 1; fi
+INDEXER="indexer --config SYSCONFDIR/piler/${CONFIG_FILE}"
+
+if [[ -f "$MAINTMPFILE" ]]; then echo "INDEXER ERROR: indexer merging to main index is already running. It started at $(cat "$MAINTMPFILE")" | logger -p "$PRIORITY" ; exit 1; fi
+
+if [[ -f "$DELTATMPFILE" ]]; then echo "INDEXER ERROR: delta indexing and merging is already running. It started at $(cat "$DELTATMPFILE")" | logger -p "$PRIORITY" ; exit 1; fi
 
 date > $DELTATMPFILE
 
@@ -34,4 +41,3 @@ echo "INDEXER INFO: merging delta to dailydelta started" | logger -p $PRIORITY
 $INDEXER --quiet --merge dailydelta1 delta1 --merge-dst-range deleted 0 0 --rotate
 
 echo "INDEXER INFO: merging delta to dailydelta finished" | logger -p $PRIORITY
-
