postinstall fixes
Signed-off-by: Janos SUTO <sj@acts.hu>

diff --git a/util/postinstall.sh.in b/util/postinstall.sh.in
--- a/util/postinstall.sh.in
+++ b/util/postinstall.sh.in
@@ -4,9 +4,6 @@ set -o nounset
 set -o errexit
 set -o pipefail
 
-SCRIPT_PATH="$(readlink -f "$0")"
-SCRIPT_DIR="${SCRIPT_PATH%/*}"
-
 INDEXER="$(command -v indexer)"
 SEARCHD="$(command -v searchd)"
 CRON_ORIG="/tmp/crontab.piler.orig"
@@ -248,7 +245,6 @@ gather_mysql_account() {
    # shellcheck disable=SC2181
    if [[ $? -eq 0 ]]; then
       echo "mysql connection successful"; echo;
-      if [[ $(echo "$s" | grep -c metadata) -eq 1 ]]; then echo "ERROR: Detected metadata table in ${MYSQL_DATABASE}. Aborting"; exit 0; fi
    else
       echo "ERROR: failed to connect to mysql";
       gather_mysql_account
@@ -353,6 +349,7 @@ show_summary() {
 
 
 execute_post_install_tasks() {
+   local create_db=1
 
    askYN "Continue and modify system? [Y/N]" "N"
    if [[ "$response" != "yes" ]]; then
@@ -360,11 +357,23 @@ execute_post_install_tasks() {
       exit
    fi
 
-   echo;
-   echo -n "Creating mysql database... ";
-   sed -e "s%MYSQL_HOSTNAME%${MYSQL_HOSTNAME}%g" -e "s%MYSQL_DATABASE%${MYSQL_DATABASE}%g" -e "s%MYSQL_USERNAME%${MYSQL_USERNAME}%g" -e "s%MYSQL_PASSWORD%${MYSQL_PASSWORD}%g" "${DATAROOTDIR}/piler/db-mysql-root.sql.in" | mysql -h "$MYSQL_HOSTNAME" -u root --password="$MYSQL_ROOT_PASSWORD"
-   mysql -h "$MYSQL_HOSTNAME" -u "$MYSQL_USERNAME" --password="$MYSQL_PASSWORD" "$MYSQL_DATABASE" < "${DATAROOTDIR}/piler/db-mysql.sql"
-   echo "Done."
+   s=$(echo "use information_schema; select TABLE_NAME from TABLES where TABLE_SCHEMA='${MYSQL_DATABASE}'" | mysql -h "$MYSQL_HOSTNAME" -u root --password="$MYSQL_ROOT_PASSWORD")
+   # shellcheck disable=SC2181
+   if [[ $? -eq 0 ]]; then
+      echo "mysql connection successful"; echo;
+      if [[ $(echo "$s" | grep -c metadata) -eq 1 ]]; then echo "ERROR: Detected metadata table in ${MYSQL_DATABASE}."; create_db=0; fi
+   else
+      echo "ERROR: failed to connect to mysql";
+      exit 1
+   fi
+
+   if [[ $create_db -eq 1 ]]; then
+      echo
+      echo -n "Creating mysql database... ";
+      sed -e "s%MYSQL_HOSTNAME%${MYSQL_HOSTNAME}%g" -e "s%MYSQL_DATABASE%${MYSQL_DATABASE}%g" -e "s%MYSQL_USERNAME%${MYSQL_USERNAME}%g" -e "s%MYSQL_PASSWORD%${MYSQL_PASSWORD}%g" "${DATAROOTDIR}/piler/db-mysql-root.sql.in" | mysql -h "$MYSQL_HOSTNAME" -u root --password="$MYSQL_ROOT_PASSWORD"
+      mysql -h "$MYSQL_HOSTNAME" -u "$MYSQL_USERNAME" --password="$MYSQL_PASSWORD" "$MYSQL_DATABASE" < "${DATAROOTDIR}/piler/db-mysql.sql"
+      echo "Done."
+   fi
 
    echo -n "Writing manticore configuration... ";
    sed -e "s%MYSQL_HOSTNAME%${MYSQL_HOSTNAME}%" -e "s%MYSQL_DATABASE%${MYSQL_DATABASE}%" -e "s%MYSQL_USERNAME%${MYSQL_USERNAME}%" -e "s%MYSQL_PASSWORD%${MYSQL_PASSWORD}%" "${SYSCONFDIR}/piler/manticore.conf.dist" > "$SEARCHCFG"
@@ -386,7 +395,29 @@ execute_post_install_tasks() {
    echo "Fix piler.conf path in pilerpurge.py"
    sed -i "s%\/etc\/piler\/piler\.conf%${SYSCONFDIR}\/piler\/piler\.conf%" "${LIBEXECDIR}/piler/pilerpurge.py"
 
-   envsubst < "${SCRIPT_DIR}/config-site.php.in" | sed s%config%\$config%g > "$CONFIG_SITE_PHP"
+   cat > "$CONFIG_SITE_PHP" << EOF
+<?php
+
+\$config['SITE_NAME'] = '$HOSTNAME';
+\$config['PATH_PREFIX'] = '/';
+\$config['SITE_URL'] = 'http://' . config['SITE_NAME'] . config['PATH_PREFIX'];
+\$config['DIR_BASE'] = '$DOCROOT/';
+
+\$config['SMTP_DOMAIN'] = '$HOSTNAME';
+\$config['SMTP_FROMADDR'] = 'no-reply@' . config['SMTP_DOMAIN'];
+\$config['ADMIN_EMAIL'] = 'admin@' . config['SMTP_DOMAIN'];
+
+\$config['DB_DRIVER'] = 'mysql';
+\$config['DB_PREFIX'] = '';
+\$config['DB_HOSTNAME'] = '$MYSQL_HOSTNAME';
+\$config['DB_USERNAME'] = '$MYSQL_USERNAME';
+\$config['DB_PASSWORD'] = '$MYSQL_PASSWORD';
+\$config['DB_DATABASE'] = '$MYSQL_DATABASE';
+
+\$config['SMARTHOST'] = '$SMARTHOST';
+\$config['SMARTHOST_PORT'] = '$SMARTHOST_PORT';
+\$config['RT'] = $RT;
+EOF
 
    make_certificate
 
