Updated postinstall script
Signed-off-by: Janos SUTO <sj@acts.hu>

diff --git a/util/postinstall.sh.in b/util/postinstall.sh.in
--- a/util/postinstall.sh.in
+++ b/util/postinstall.sh.in
@@ -24,7 +24,6 @@ load_default_values() {
    PILER_CONFIG_DIR="${SYSCONFDIR}/piler"
    CONFIG_SITE_PHP="${PILER_CONFIG_DIR}/config-site.php"
 
-   KEYTMPFILE="piler.key"
    KEYFILE="${PILER_CONFIG_DIR}/piler.key"
 
    HOSTNAME="$(hostname --fqdn)"
@@ -46,7 +45,7 @@ load_default_values() {
    SMARTHOST=""
    SMARTHOST_PORT=25
 
-   SSL_CERT_DATA="/C=US/ST=Denial/L=Springfield/O=Dis/CN=archive.example.com"
+   SSL_CERT_DATA="/C=HU/ST=Pest/L=Budapest/O=Example/CN=archive.example.com"
 }
 
 
@@ -204,8 +203,6 @@ preinstall_check() {
    if [[ "$INDEXER" == "" ]]; then "ERROR: cannot find indexer binary"; echo ""; exit ; fi
 
    if [[ "$SEARCHD" == "" ]]; then "ERROR: cannot find searchd binary"; echo ""; exit 0; fi
-
-   if [[ -f "$KEYFILE" ]]; then echo "ERROR: found existing keyfile (${KEYFILE}), aborting install"; echo ""; exit 0; fi
 }
 
 
@@ -302,9 +299,12 @@ make_cron_entries() {
 
 
 make_new_key() {
-   dd if=/dev/urandom bs=56 count=1 of="$KEYTMPFILE" 2>/dev/null
-
-   if [ "$(stat -c '%s' "$KEYTMPFILE")" -ne 56 ]; then echo "could not read 56 bytes from /dev/urandom to ${KEYTMPFILE}"; exit 1; fi
+   if [[ ! -f "$KEYFILE" ]]; then
+      dd if=/dev/urandom bs=56 count=1 of="$KEYFILE" 2>/dev/null
+      if [ "$(stat -c '%s' "$KEYFILE")" -ne 64 ]; then echo "could not read 64 bytes from /dev/urandom to ${KEYFILE}"; exit 1; fi
+      chgrp "$PILERUSER" "$KEYFILE"
+      chmod 640 "$KEYFILE"
+   fi
 }
 
 
@@ -349,7 +349,6 @@ show_summary() {
       echo "Aborted."
       exit
    fi
-
 }
 
 
@@ -383,13 +382,6 @@ execute_post_install_tasks() {
    crontab -u "$PILERUSER" "$CRON_TMP"
    echo "Done."
 
-
-   echo -n "installing keyfile (${KEYTMPFILE}) to ${KEYFILE}... "
-   cp "$KEYTMPFILE" "$KEYFILE"
-   chgrp "$PILERUSER" "$KEYFILE"
-   chmod 640 "$KEYFILE"
-   rm -f "$KEYTMPFILE"
-   echo "Done."
 
    echo "Fix piler.conf path in pilerpurge.py"
    sed -i "s%\/etc\/piler\/piler\.conf%${SYSCONFDIR}\/piler\/piler\.conf%" "${LIBEXECDIR}/piler/pilerpurge.py"
@@ -425,13 +417,7 @@ SOCKHELPER
       cp webui/.htaccess "$DOCROOT"
    fi
 
-   if [[ -d /var/www/piler.example.com ]]; then
-      mv /var/www/piler.example.com "$DOCROOT"
-   fi
-
-
    if [[ -d "$DOCROOT" ]]; then webui_install; fi
-
 }
 
 
